### Carbon Python Sample No.01 - Simple Report

An array of values is passed as a request into the Plutonium web service. The Carbon cross-tabulation engine response contains JSON in the exact shape required for conversion into a pandas dataframe.

In [4]:
import requests
import json
import pandas
import matplotlib.pyplot as plt
from pyparsing import line

postdata={
  "id": "10000010",
  "password": "free",
  "name": "Example 02",
  "customerName": "rcsruby",
  "jobName": "demo",
  "top": "Age",
  "side": "Region",
  "filter": None,
  "weight": None,
  "columnPercents": False,
  "formatType": 1,
  "overrideLicensingbaseAddress": None,
  "skipCache": False
}
response = requests.post("https://rcsapps.azurewebsites.net/plutonium/python/crosstab/gentab", json=postdata)
dfjson = response.json()
df=pandas.DataFrame(dfjson)
df

      15-25 26-35 36-50 51-65  65+ Under 35 Over 35 Under 50 Over 50
NE       41    53    44    45   55    94.00  144.00   138.00  100.00
SE       43    48    49    52   46    91.00  147.00   140.00   98.00
SW       48    38    42    67   52    86.00  161.00   128.00  119.00
NW       40    58    68    58   53    98.00  179.00   166.00  111.00
East     84   101    93    97  101   185.00  291.00   278.00  198.00
West     88    96   110   125  105   184.00  340.00   294.00  230.00
North    81   111   112   103  108   192.00  323.00   304.00  211.00
South    91    86    91   119   98   177.00  308.00   268.00  217.00